// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALE0XLdTO3KYANXDnLDIKPIwOZtDzOniU',
    appId: '1:1005254691200:android:c537e79239470e4a009965',
    messagingSenderId: '1005254691200',
    projectId: 'nurse-todo',
    storageBucket: 'nurse-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtD9hNOixB_Tn9nAWiWk38872qlObqXs',
    appId: '1:1005254691200:ios:a4357ca9c4446217009965',
    messagingSenderId: '1005254691200',
    projectId: 'nurse-todo',
    storageBucket: 'nurse-todo.appspot.com',
    androidClientId: '1005254691200-tous9u41f3414e1k0bgr7aclh2165uc0.apps.googleusercontent.com',
    iosClientId: '1005254691200-hrege5s6f3auand39lcm19ungalhm000.apps.googleusercontent.com',
    iosBundleId: 'com.nursetodo.app',
  );
}
